Update s3 bucket creation script
ArtBlocks/artblocks-contracts pull request #667
Opened 2023-04-26 23:32 UTC by ryley-o

## Description of the change

Incorporate required updates, as described here:

https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

2023-04-26 23:34 UTC, jakerockland approved these changes
🙏 Thank you thank you thank you @ryley-o

2023-04-26 23:39 UTC, lyaunzbe approved these changes

2023-04-26 23:39 UTC, lyaunzbe commented on scripts/util/aws_s3.ts
> +  const response = await client.send(command);
this needs to be command2

2023-04-26 23:39 UTC, lyaunzbe commented on scripts/util/aws_s3.ts
> +  return await client.send(command);
needs to be command3

2023-04-26 23:39 UTC, lyaunzbe requested changes
woops meant to request on the prev review

2023-04-27 03:58 UTC, ryley-o commented on scripts/util/aws_s3.ts
> +  const response = await client.send(command);
oops, thanks and updated!

2023-04-27 03:58 UTC, ryley-o commented on scripts/util/aws_s3.ts
> +  return await client.send(command);
oops, thanks and updated!

2023-04-27 04:39 UTC, lyaunzbe approved these changes

2023-04-27 04:51 UTC, merged